#!/bin/bash
ulimit -s unlimited

NUMA="numactl -m 0"
#NUMA="numactl -m 1"

${NUMA} /work1/compiler-beta/advisor_2018.0.2.506306/bin64/advixe-cl -collect survey -no-auto-finalize -project-dir /usr/people/wohlbier/devel/stream/DRAM -- /usr/people/wohlbier/devel/stream/stream_f.exe
${NUMA} /work1/compiler-beta/advisor_2018.0.2.506306/bin64/advixe-cl -collect tripcounts -flops-and-masks -project-dir /usr/people/wohlbier/devel/stream/DRAM -- /usr/people/wohlbier/devel/stream/stream_f.exe
