#!/bin/tcsh

#PBS -N stream
#PBS -l nodes=1:ppn=72:skylake
#PBS -l walltime=10:00
#PBS -j oe

module load llvm-5.0.0-gcc-7.1.0-krxbfjg
module load flang-develop-gcc-7.1.0-7rrbbfa

cd $PBS_O_WORKDIR
setenv OMP_DISPLAY_ENV true

#setenv OMP_NUM_THREADS 1
setenv OMP_NUM_THREADS 18
#setenv OMP_NUM_THREADS 36

setenv OMP_PROC_BIND close
setenv OMP_PLACES cores

numactl -C 0-17 ./stream_f.exe
numactl -C 0-17 ./stream_c.exe
