#!/bin/tcsh

#PBS -N stream
#PBS -l nodes=1:ppn=128:b0
#PBS -l walltime=10:00
#PBS -j oe

module load gcc/7.2

cd $PBS_O_WORKDIR
setenv OMP_DISPLAY_ENV true
setenv OMP_PROC_BIND close
setenv OMP_PLACES cores

setenv OMP_NUM_THREADS 1
./stream_f.exe
./stream_c.exe

setenv OMP_NUM_THREADS 32
./stream_f.exe
./stream_c.exe

setenv OMP_PLACES threads
setenv OMP_NUM_THREADS 64
./stream_f.exe
./stream_c.exe
